server:
  port: 10010

logging:
  file: /opt/WDN/LOGS/14_SpringTest_Assignment1.log
  level:
    root: info

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver